# Generated by Django 2.0.2 on 2018-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0008_remove_medium_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='rating_number',
            new_name='Happiness',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='medium',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='salary_number',
            new_name='SalaryPerMonthEmpMix',
        ),
        migrations.RenameField(
            model_name='medium',
            old_name='festfrei',
            new_name='freeoremployed',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='CharPerArticleFree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='Comment',
            field=models.CharField(default='Kein Kommentar', max_length=600),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='DaysPerMonthMix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='Experience',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keineAngabe', max_length=10),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='FeeFree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='Genre',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='HoursPerDayMix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='HoursPerWeekEmp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='HoursSpentFree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='JobPosition',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='MinPerAudioFree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='MinPerVideoFree',
            field=models.IntegerField(default=0),
        ),
    ]
