# Generated by Django 2.0.2 on 2018-03-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0009_auto_20180306_1412'),
        ('honoradar', '0017_auto_20180302_0646'),
    ]

    operations = [
    ]
